apiVersion: v1
kind: ConfigMap
metadata:
  name: xlink-config
  namespace: xlink
data:
  SERVER_PORT: "8080"
  SERVER_BASE_URL: "http://xlink-service.xlink.svc.cluster.local:8080"
  DB_URL: "postgres://xlink_user:xlink_secret_password_2026@postgres.xlink.svc.cluster.local:5432/xlink_db?sslmode=disable"
  REDIS_URL: "redis://redis.xlink.svc.cluster.local:6379/0"
  LOG_LEVEL: "info"
  LOG_FORMAT: "json"
  CACHE_L1_MAX_COST_MB: "512"
  CACHE_L1_NUM_COUNTERS: "10000000"
  PPROF_ENABLED: "true"
  OTEL_EXPORTER_OTLP_ENDPOINT: "jaeger.xlink.svc.cluster.local:4317"
  OTEL_SERVICE_NAME: "xlink-api"
  OTEL_ENVIRONMENT: "kubernetes-production"
---
apiVersion: v1
kind: Secret
metadata:
  name: xlink-secrets
  namespace: xlink
type: Opaque
stringData:
  AUTH_JWT_SECRET: "xlink-super-secret-jwt-key-2026-cloud-native-k8s"
  POSTGRES_USER: "xlink_user"
  POSTGRES_PASSWORD: "xlink_secret_password_2026"
  POSTGRES_DB: "xlink_db"
