global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: 'xlink_api'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['host.docker.internal:8080', '10.0.1.191:8080']
        labels:
          app: 'xlink'
          env: 'production'
